### PR TITLE
8305906: HttpClient may use incorrect key when finding pooled HTTP/2 connection for IPv6 address

### PR DESCRIPTION
**Pull request by varada1110**
Hi all,

This pull request contains a backport of commit [43956686](https://github.com/openjdk/jdk17u-dev/commit/43956686c924658ee2d7866e46ee9f10d9595c35) from the [openjdk/jdk17u-dev](https://git.openjdk.org/jdk17u-dev) repository.

The commit being backported was authored by Jaikiran Pai on 16 Feb 2024 and was reviewed by Paul Hohensee.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8305906](https://bugs.openjdk.org/browse/JDK-8305906) needs maintainer approval

### Issue
 * [JDK-8305906](https://bugs.openjdk.org/browse/JDK-8305906): HttpClient may use incorrect key when finding pooled HTTP/2 connection for IPv6 address (**Bug** - P4 - Approved)

### Reviewers
 * [Jaikiran Pai](https://openjdk.org/census#jpai) (@jaikiran - no project role) ⚠️ Review applies to [b192d63e](https://git.openjdk.org/jdk11u-dev/pull/2531/files/b192d63e452f5528703e09f09655d2ee1cec9f9c)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [b192d63e](https://git.openjdk.org/jdk11u-dev/pull/2531/files/b192d63e452f5528703e09f09655d2ee1cec9f9c)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2531/head:pull/2531` \
`$ git checkout pull/2531`

Update a local copy of the PR: \
`$ git checkout pull/2531` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2531/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2531`

View PR using the GUI difftool: \
`$ git pr show -t 2531`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2531.diff">https://git.openjdk.org/jdk11u-dev/pull/2531.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2531#issuecomment-1951892100)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @varada1110 ,
I think you don't need the test adaptions to SimpleSSLContext.  But the test will not work with jtreg 6.1 as it uses jupiter code not in jtreg 6.1.  Make sure your local tests for 11 use jtreg 6.1.

test/jdk/java/net/httpclient/http2/ConnectionReuseTest.java:41: error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.AfterAll;

**Comment by varada1110** [comment]
Thanks @GoeLin for pointing that out. I tested with wrong jtreg version. I will fix the errors.

**Comment by varada1110** [comment]
Hi @GoeLin, can you please review the changes. Test is passing now with jtreg 6.1

**Comment by varada1110** [comment]
@jaikiran @GoeLin  Could you please review the code? 
Thank you,
Varada

**Comment by offamitkumar** [comment]
@phohensee would you be able to take a look at this, as you reviewed the head PR as well.

**Review by jaikiran — APPROVED** [review]
The source changes look OK to me and matches the changes that were done in mainline. The test looks OK too. But do note that I haven't run it against JDK 11u to ascertain that the test work as expected. As long as the test fails without the source changes and passes with the source changes, I think this is fine.

I am not involved in JDK update project, so before integrating, please also have this approved by someone who is involved in JDK updates project.

**Comment by varada1110** [comment]
Thank you @jaikiran for reviewing the changes.

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
GHA failures appear infrastructure related.

**Comment by offamitkumar** [comment]
>/approval request The GHA failures seems to be infrastructure-related issues.

no, this is not valid reason for the approval.

You need to mention "why" you want to backport this change, what issue you're fixing here ?

**Comment by offamitkumar** [comment]
use it like this : `/approval JDK-8305906 request <your reason>`

**Comment by offamitkumar** [comment]
/approval request org.junit.jupiter.api is not supported. Therefore, I have added the similar annotations supported by org.junit.*

@varada1110 I think instead of `editing` the comment you need to post a separate new comment, so that bot picks it up again.

**Comment by varada1110** [comment]
/approval request org.junit.jupiter.api is not supported. Therefore, I have added the similar annotations supported by org.junit.*

**Comment by varada1110** [comment]
/approval JDK-8305906 request org.junit.jupiter.api is not supported. Therefore, I have added the similar annotations supported by org.junit.*

**Comment by GoeLin** [comment]
Hi @varada1110
please explain how you addressed the issues that came up in the 17u backport.  Also explain how you tested to show the same issues don't surface in 11.
Please rerun the GHA tests.

**Comment by varada1110** [comment]
Hi @GoeLin , Could you please review the code? All checks have passed and test is passing with updated jtreg

**Comment by TheRealMDoerr** [comment]
This PR is clean and can apply for maintainer approval.

**Comment by varada1110** [comment]
/approval JDK-8305906 request test is passing with updated jtreg and PR is clean.
